### ISSUE TITLE
Incluir 918 Los Yatagarasu del Milegu

### ISSUE THREAD

**Issue by Avengium** [Jakeukalane/jakeukalane.github.io#3]
Los artículos son:
919	Khloris
918	Los Yatagarasu del Milegu
917	Los Kelpies del Milegu

Pero en la Versión 23 de abril de 2019 (4.47.) del indice publico aparece;
07/04/2018 - Khloris
22/03/2018 - Los Kelpies del Milegu

Propongo añadir: 
http://tuscriaturas.blogia.com/2018/032801-los-yatagarasu-del-milegu.php
como:
28/03/2018 - Los Yatagarasu del Milegu

**Comment by Jakeukalane** [comment]
Solved :D Thank you!
